name: ci
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
            # A string to determine the format of the version output
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
            # Optional path to check for changes. If any changes are detected in the path the
            # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "src/"
          bump_each_commit: false
            # If bump_each_commit is also set to true, setting this value will cause the version to increment only if the pattern specified is matched.
          bump_each_commit_patch_pattern: ""
          search_commit_body: false
            # The output method used to generate list of users, 'csv' or 'json'.
          user_format_type: "csv"
            # Prevents pre-v1.0.0 version from automatically incrementing the major version.
            # If enabled, when the major version is 0, major releases will be treated as minor and minor as patch. Note that the version_type output is unchanged.
          enable_prerelease_mode: true
