name: ci
on:
  push:
  pull_request:
  workflow_dispatch:

# Spend CI time only on latest ref: https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ i686-unknown-linux-gnu, x86_64-unknown-linux-gnu ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Install gcc-libs
        run: |
          sudo apt install gcc-multilib

      # related to https://github.com/actions/runner/issues/2468 
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          # use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      
      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          TAR_NAME=$(printf "reberzug-%s.tar.gz" $(echo ${{ matrix.target }} | sed 's/-unknown//g' ) )

          tar czvf ../../../${TAR_NAME} reberzug
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: 'reberzug*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  fmt:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check
        run: cargo fmt --check
